kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-enterprise-admission
subjects:
- kind: ServiceAccount
  namespace: NAMESPACE_OF_SERVICE_ACCOUNT
  name: redis-enterprise-admission
roleRef:
  kind: ClusterRole
  name: redis-enterprise-admission
  apiGroup: rbac.authorization.k8s.io
